### ISSUE TITLE
请问能否更新一下release，我发现那些都是上个学期的了，或者说能否简要地写一下这些脚本该怎么用？万分感谢！

### ISSUE THREAD

**Issue by Outofnothing** [CourierKyn/scut-icalendar#1]

**Comment by CourierKyn** [comment]
安装依赖：`pip install beautifulsoup4 icalendar`
运行：`python parse.py`

此程序将从同一目录下的 html 教务页面生成 ics 日历文件

获取教务页面方法如下，以 Chrome 为例：

<img width="367" alt="2018-09-27 9 59 12" src="https://user-images.githubusercontent.com/29699904/46151453-641dd500-c2a1-11e8-95bc-90bb473368ba.png">

然后右键源代码页面 > 另存为 > 选择仅 HTML。
